name: cecilia
favicon: null
layout_spectrum: 0.7962648451793939
typography_spectrum: 0.33017050428315997
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4125453184824437
  lightness: 0.3737345461267978
  saturation: 0.34764391486532986
  rhythmicContrast: 0.5480418228544295
purpose: []
